### ISSUE TITLE
Load Lato font

### ISSUE THREAD

**Issue by vidonne** [vidonne/unhcrthemes#8]
Find the best way to load the Lato font so it can be used in the charts. Extrafont vs showtext vs custom function or simply the use of ragg when saving the plot?

**Comment by dickoa** [comment]
Hi @vidonne 

A PR to automatically load Lato on startup, it uses `showtext` for vector devices and `ragg`  for bitmap.

https://github.com/vidonne/unhcrthemes/pull/14
